---
- hosts: localhost
  gather_facts: false

  tasks:
    - name: Get hostname
      command: hostname
      register: hostname_output

    - name: Display hostname
      debug:
        var: hostname_output.stdout
