---
- name: Mettre à jour CentoOS et installer htop
  hosts: all
  become: yes
  tasks:
    - name: Configurer le serveur DNS à 8.8.8.8
      ansible.builtin.lineinfile:
        dest: /etc/resolv.conf
        regexp: '^nameserver'
        line: 'nameserver 8.8.8.8'
        state: present
        
    - name: Ajouter le dépôt EPEL
      ansible.builtin.yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: https://download.fedoraproject.org/pub/epel/7/$basearch
        gpgcheck: yes
        gpgkey: https://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
        enabled: yes
        state: present
        
    - name: Mettre à jour la liste des paquets
      ansible.builtin.yum:
        update_cache: yes

    - name: Mettre à jour tous les paquets installés
      ansible.builtin.yum:
        name: '*'
        state: latest

    - name: Installer le paquet htop
      ansible.builtin.yum:
        name: htop
        state: present

    - name: Supprimer les paquets inutiles
      ansible.builtin.yum:
        autoremove: yes
