---
- name: Mettre à jour Rocky OS et installer htop
  hosts: all
  become: yes
  tasks:
    - name: Mettre à jour la liste des paquets
      ansible.builtin.yum:
        update_cache: yes

    - name: Mettre à jour tous les paquets installés
      ansible.builtin.yum:
        name: '*'
        state: latest

    - name: Installer le paquet htop
      ansible.builtin.yum:
        name: htop
        state: present

    - name: Supprimer les paquets inutiles
      ansible.builtin.yum:
        autoremove: yes
