---
- name: Mettre à jour le système et installer htop
  hosts: all
  become: yes
  tasks:
    - name: Mettre à jour la liste des paquets
      ansible.builtin.apt:
        update_cache: yes

    - name: Installer le paquet htop
      ansible.builtin.apt:
        name: htop
        state: present
